import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import HeaderMenu from "@/components/Header/menu";
import ClientProvider from "@/lib/ClientProvider"; 
import Footer from "@/components/Footer";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ClientProvider> {/* Encapsulation du contexte Apollo */}
        <header className="fixed  left-0 w-full z-50 flex items-center  px-6 h-20 bg-[#020202]">
  {/* LOGO */}
  <div className="text-2xl font-bold flex items-center ">
    <a href="/">
      <img
        src="/logo.png"
        alt="Logo"
        className="h-24 w-auto" // Taille ajustée
      />
    </a>
  </div>

  {/* MENU */}
  <div className="flex items-center h-full">
    <HeaderMenu />
  </div>
</header>
          <div className="pt-24 mx-auto">{children}</div>
          <Footer />
        </ClientProvider>
      </body>
    </html>
  );
}